<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                "id" => 1,
                "added_by" => null,
                "name" => "Settings",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "0",
                "permission" => "view academic years",
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 2,
                "added_by" => null,
                "name" => "Academic Year",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/academicyears",
                "icon" => null,
                "position" => "0",
                "permission" => "view academic years",
                "is_active" => "1",
                "is_searchable" => "0",
            ],

            [
                "id" => 4,
                "added_by" => null,
                "name" => "Menu Setting",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "1",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 5,
                "added_by" => null,
                "name" => "Menu",
                "parent_id" => "4",
                "is_parent" => "0",
                "url" => "/menu",
                "icon" => null,
                "position" => "1",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 6,
                "added_by" => null,
                "name" => "Theme",
                "parent_id" => "4",
                "is_parent" => "0",
                "url" => "/theme",
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 8,
                "added_by" => null,
                "name" => "Manager Users",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 9,
                "added_by" => null,
                "name" => "Users",
                "parent_id" => "8",
                "is_parent" => "0",
                "url" => "/users",
                "icon" => null,
                "position" => "0",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 10,
                "added_by" => null,
                "name" => "Permission",
                "parent_id" => "8",
                "is_parent" => "0",
                "url" => "/permissions",
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 11,
                "added_by" => null,
                "name" => "Roles",
                "parent_id" => "8",
                "is_parent" => "0",
                "url" => "/users/roles",
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 13,
                "added_by" => null,
                "name" => "Academics",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 14,
                "added_by" => null,
                "name" => "Universities",
                "parent_id" => "13",
                "is_parent" => "0",
                "url" => "/academics/university",
                "icon" => null,
                "position" => "1",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 15,
                "added_by" => null,
                "name" => "Department",
                "parent_id" => "13",
                "is_parent" => "0",
                "url" => "/academics/department",
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 16,
                "added_by" => null,
                "name" => "Course",
                "parent_id" => "13",
                "is_parent" => "0",
                "url" => "/academics/course",
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 17,
                "added_by" => null,
                "name" => "Sub Course",
                "parent_id" => "13",
                "is_parent" => "0",
                "url" => "/academics/subcourse",
                "icon" => null,
                "position" => "4",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 18,
                "added_by" => null,
                "name" => "Subject",
                "parent_id" => "13",
                "is_parent" => "0",
                "url" => "/academics/subjects",
                "icon" => null,
                "position" => "5",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 19,
                "added_by" => null,
                "name" => "Course Type",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/coursetypes",
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 20,
                "added_by" => null,
                "name" => "Admission Modes",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/admissionmodes",
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 21,
                "added_by" => null,
                "name" => "Course Modes",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/coursemodes",
                "icon" => null,
                "position" => "4",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 22,
                "added_by" => null,
                "name" => "Language",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/languages",
                "icon" => null,
                "position" => "6",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 23,
                "added_by" => null,
                "name" => "Blood Group",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/bloodgroups",
                "icon" => null,
                "position" => "7",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 24,
                "added_by" => null,
                "name" => "Category",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/categories",
                "icon" => null,
                "position" => "8",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 25,
                "added_by" => null,
                "name" => "Religion",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/religions",
                "icon" => null,
                "position" => "9",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 26,
                "added_by" => null,
                "name" => "Student",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "5",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 27,
                "added_by" => null,
                "name" => "Apply Fresh",
                "parent_id" => "26",
                "is_parent" => "0",
                "url" => "/students/create",
                "icon" => null,
                "position" => "1",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 28,
                "added_by" => null,
                "name" => "All Application",
                "parent_id" => "26",
                "is_parent" => "0",
                "url" => "/students",
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 29,
                "added_by" => null,
                "name" => "Accounts",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "5",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 34,
                "added_by" => null,
                "name" => "Reports",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => null,
                "icon" => null,
                "position" => "5",
                "permission" => "view reports",
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 30,
                "added_by" => null,
                "name" => "Student Receipt",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/accounts/fees",
                "icon" => null,
                "position" => "1",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 31,
                "added_by" => null,
                "name" => "Student Ledger",
                "parent_id" => "29",
                "is_parent" => "0",
                "url" => "/accounts/studentindex",
                "icon" => null,
                "position" => "2",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 32,
                "added_by" => null,
                "name" => "University Fees",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/accounts/university-fee",
                "icon" => null,
                "position" => "3",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 33,
                "added_by" => null,
                "name" => "University Payments",
                "parent_id" => "29",
                "is_parent" => "0",
                "url" => "/accounts/university-payments",
                "icon" => null,
                "position" => "4",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],

            [
                "id" => 35,
                "added_by" => null,
                "name" => "Students Reports",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/reports/students",
                "icon" => null,
                "position" => "1",
                "permission" => "create reports",
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 36,
                "added_by" => null,
                "name" => "Pending fees Reports",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/reports/pendingfees",
                "icon" => null,
                "position" => "4",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 37,
                "added_by" => null,
                "name" => "Income Reports",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/reports/income",
                "icon" => null,
                "position" => "5",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 38,
                "added_by" => null,
                "name" => "Expense Reports",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/reports/expence",
                "icon" => null,
                "position" => "6",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 39,
                "added_by" => null,
                "name" => "Status",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/status",
                "icon" => null,
                "position" => "10",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 40,
                "added_by" => null,
                "name" => "Query Head",
                "parent_id" => "1",
                "is_parent" => "0",
                "url" => "/settings/queryhead",
                "icon" => null,
                "position" => "11",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 41,
                "added_by" => null,
                "name" => "Income & Expences",
                "parent_id" => "34",
                "is_parent" => "0",
                "url" => "/reports/profit",
                "icon" => null,
                "position" => "8",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 42,
                "added_by" => null,
                "name" => "Front Desk",
                "parent_id" => null,
                "is_parent" => "0",
                "url" => "/students/index",
                "icon" => null,
                "position" => "8",
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],


            // New menus
            [
                "id" => 43,
                "added_by" => null,
                "name" => "Expense Category",
                "parent_id" => 1,
                "is_parent" => "0",
                "url" => "/settings/expensecategory",
                "icon" => null,
                "position" => 11,
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 44,
                "added_by" => null,
                "name" => "Voucher",
                "parent_id" => 29,
                "is_parent" => "0",
                "url" => "/accounts/vouchers",
                "icon" => null,
                "position" => 3,
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],
            [
                "id" => 45,
                "added_by" => null,
                "name" => "Voucher Payment",
                "parent_id" => 29,
                "is_parent" => "0",
                "url" => "/accounts/payments",
                "icon" => null,
                "position" => 4,
                "permission" => null,
                "is_active" => "1",
                "is_searchable" => "0",
            ],

            [
                "id" => 46, // Make sure this ID is unique
                "added_by" => null,
                "name" => " Student Documents",
                "parent_id" => 1,
                "is_parent" => "0",
                "url" => "/settings/document",
                "icon" => null,
                "position" => 12, // Adjust the position according to your menu order
                "permission" => null, // Optional, if using permissions
                "is_active" => "1",
                "is_searchable" => "0",
            ],
        ];

        foreach ($menus as $menu) {
            // Check if menu already exists by name
            $exists = DB::table('menus')->where('name', $menu['name'])->exists();

            if (!$exists) {
                DB::table('menus')->insert($menu);
                $this->command->info("✅ Menu '{$menu['name']}' added.");
            } else {
                $this->command->warn("⚠️ Menu '{$menu['name']}' already exists — skipped.");
            }
        }
    }
}
